name: Build and publish release

on:
  workflow_dispatch:

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Run tests and build release artifacts
      run: |
        ./gradlew test
        ./gradlew assembleRelease --stacktrace
        ./gradlew bundleRelease

    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-apk]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
        trim: true

    - name: Set full version
      run: |
        echo "VERSION=1.${{ steps.version.outputs.content }}" >> "$GITHUB_ENV"

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: release

    - name: Commit and push version file
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add VERSION
        git commit -m "Version $VERSION"
        git tag -a "v$VERSION" -m "Version $VERSION"
        git push origin "v$VERSION"
        git push

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release apk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app-release.apk
        asset_name: ReButton_${{ env.VERSION }}.apk"
        asset_content_type: application/octet-stream

    - name: Summary
      run: |
        echo "Release v$VERSION created" >> $GITHUB_STEP_SUMMARY
